sudo: required 
services:
        - docker

before_install:
        - docker build -t mnarangptc/docker-react -f Dockerfile.dev .
    
script:
        - docker run -e CI=true mnarangptc/docker-react npm run test